/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author w10
 */
import java.io.File;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

public class PanelRuta extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form PanelRuta
     */
    boolean buit;
    Thread th;
    JButton jbutton;
    private File f;
    boolean nopdfs = true;
    private ArrayList<File> llistaPDF;

    public PanelRuta(JButton B_seguent) {
        initComponents();
        buit = true;
        this.jbutton = B_seguent;
        llistaPDF = new ArrayList<File>();
        th = new Thread((Runnable) this);
        th.start();
    }

    public File getf() {
        return f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RutaText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BExplorar = new javax.swing.JButton();

        RutaText.setEditable(false);
        RutaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Ruta de la carpeta:");

        BExplorar.setText("Explorar");
        BExplorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExplorarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(RutaText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BExplorar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BExplorar)
                    .addComponent(RutaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RutaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RutaTextActionPerformed

    private void BExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExplorarActionPerformed
        // TODO add your handling code here:
        //Filtro que llegir els archius xml
//        File archiuXMLLlegir;
        llistaPDF.clear();
        FileFilter filtro = new FileNameExtensionFilter("Archius PDF", "pdf", "PDF");
        //Objete que s'encarrega de d'obrir el filechooser
        JFileChooser fileChooser = new JFileChooser("/home/linuxpc/Documentos/");
        //Añadeix el filtre dessitjat
        fileChooser.addChoosableFileFilter(filtro);
        //Selecciona el filtre dessitjat
        fileChooser.setFileFilter(filtro);
        //Lleva el filtre de tot els archius
        fileChooser.setAcceptAllFileFilterUsed(false);
        //
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
//        fileChooser.setFileSelectionMode(JFileChooser.D);
        //Obrir el menu filechooser
        int seleccion = fileChooser.showOpenDialog(this);
        //Guarda el archiu seleccionat en un objecte
        f = fileChooser.getSelectedFile();
//        Comproba que no siga null

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            String nom = "";
            File[] llista = null;
            if (f.isDirectory()) {
                System.out.println("Es un directori");
                nom = fileChooser.getSelectedFile().getPath();
//                    nom = fileChooser.getSelectedFile().getAbsolutePath();
            } else {
                nom = f.getParent();

            }
            RutaText.setText(nom);
            funcio(llista);
        }


    }//GEN-LAST:event_BExplorarActionPerformed
    public void funcio(File[] llista) {
        llista = new File(RutaText.getText()).listFiles();
        llistaPDF.clear();
        llistaArchiusPDF(llista);
    }

    public void llistaArchiusPDF(File[] llista) {
        String format = ".pdf";
        for (File file : llista) {
            //Obtinc format archiu
            String FormatArchiu = file.getName().substring(file.getName().length() - 4, file.getName().length());
            if (FormatArchiu.equals(format)) {
                llistaPDF.add(file);
            }
        }
        System.out.println("llistapdf=" + llistaPDF.size());
    }

    public ArrayList<File> getLlistaPDF() {
        return llistaPDF;
    }

    public void setLlistaPDF(ArrayList<File> llistaPDF) {
        this.llistaPDF = llistaPDF;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BExplorar;
    private javax.swing.JTextField RutaText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        jbutton.setEnabled(false);
        while (buit) {
            try {
                System.out.println("Dormint" + 500);
                Thread.sleep(500);
                System.out.println("Ha acabat de dormir");
            } catch (InterruptedException ex) {
                System.out.println("Problema en el fil");

//                Logger.getLogger(PanelRuta.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (RutaText.getText().equals("")) {
//                jbutton.setEnabled(fa);

            } else {
                if (llistaPDF.size() > 0) {
                    System.out.println("Finalitzat");
                    jbutton.setEnabled(true);
                    buit = false;
                }
            }
        }
    }
}
